"""add element_templates table

Revision ID: 223ac0a8de06
Revises: ba9dc47dbd8c
Create Date: 2026-07-08 10:34:48.767867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223ac0a8de06'
down_revision: Union[str, Sequence[str], None] = 'ba9dc47dbd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['element_templates.id'], name=op.f('fk_element_templates_parent_id_element_templates')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_element_templates_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_element_templates')),
    sa.UniqueConstraint('site_id', 'name', name=op.f('uq_element_templates_site_id'))
    )
    with op.batch_alter_table('element_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_element_templates_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_templates_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_element_templates_site_id'))
        batch_op.drop_index(batch_op.f('ix_element_templates_parent_id'))

    op.drop_table('element_templates')
    # ### end Alembic commands ###
