"""add element_templates.exclusive

Revision ID: 324d3d5cb416
Revises: 4408e06fe84b
Create Date: 2026-07-17 16:11:06.515439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324d3d5cb416'
down_revision: Union[str, Sequence[str], None] = '4408e06fe84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclusive', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_templates', schema=None) as batch_op:
        batch_op.drop_column('exclusive')

    # ### end Alembic commands ###
