"""add event_frame_attributes table

Revision ID: 75ae90dc029d
Revises: ad94e98ab812
Create Date: 2026-07-18 14:01:29.784946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ae90dc029d'
down_revision: Union[str, Sequence[str], None] = 'ad94e98ab812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_frame_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('event_frame_attribute_template_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('owns_tag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name=op.f('fk_event_frame_attributes_element_id_elements')),
    sa.ForeignKeyConstraint(['event_frame_attribute_template_id'], ['event_frame_attribute_templates.id'], name=op.f('fk_event_frame_attributes_event_frame_attribute_template_id_event_frame_attribute_templates')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_event_frame_attributes_tag_id_tags'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_frame_attributes')),
    sa.UniqueConstraint('element_id', 'event_frame_attribute_template_id', name=op.f('uq_event_frame_attributes_element_id'))
    )
    with op.batch_alter_table('event_frame_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_frame_attributes_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_attributes_event_frame_attribute_template_id'), ['event_frame_attribute_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_attributes_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_frame_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_frame_attributes_tag_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_attributes_event_frame_attribute_template_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_attributes_element_id'))

    op.drop_table('event_frame_attributes')
    # ### end Alembic commands ###
