"""add event_frame_templates table

Revision ID: 76ca67faa837
Revises: 324d3d5cb416
Create Date: 2026-07-17 16:19:02.059968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ca67faa837'
down_revision: Union[str, Sequence[str], None] = '324d3d5cb416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_frame_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_template_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['element_template_id'], ['element_templates.id'], name=op.f('fk_event_frame_templates_element_template_id_element_templates')),
    sa.ForeignKeyConstraint(['parent_id'], ['event_frame_templates.id'], name=op.f('fk_event_frame_templates_parent_id_event_frame_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_frame_templates')),
    sa.UniqueConstraint('element_template_id', 'name', name=op.f('uq_event_frame_templates_element_template_id'))
    )
    with op.batch_alter_table('event_frame_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_frame_templates_element_template_id'), ['element_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_templates_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_frame_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_frame_templates_parent_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_templates_element_template_id'))

    op.drop_table('event_frame_templates')
    # ### end Alembic commands ###
