"""add elements table

Revision ID: 7b210831a436
Revises: 223ac0a8de06
Create Date: 2026-07-08 17:31:58.962605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b210831a436'
down_revision: Union[str, Sequence[str], None] = '223ac0a8de06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_template_id', sa.Integer(), nullable=False),
    sa.Column('tag_area_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['element_template_id'], ['element_templates.id'], name=op.f('fk_elements_element_template_id_element_templates')),
    sa.ForeignKeyConstraint(['parent_id'], ['elements.id'], name=op.f('fk_elements_parent_id_elements')),
    sa.ForeignKeyConstraint(['tag_area_id'], ['areas.id'], name=op.f('fk_elements_tag_area_id_areas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elements')),
    sa.UniqueConstraint('parent_id', 'name', name=op.f('uq_elements_parent_id'))
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elements_element_template_id'), ['element_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_elements_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_elements_tag_area_id'), ['tag_area_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elements_tag_area_id'))
        batch_op.drop_index(batch_op.f('ix_elements_parent_id'))
        batch_op.drop_index(batch_op.f('ix_elements_element_template_id'))

    op.drop_table('elements')
    # ### end Alembic commands ###
