"""initial schema

Revision ID: 949027264204
Revises: 
Create Date: 2026-07-05 12:33:39.656749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949027264204'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enterprises')),
    sa.UniqueConstraint('abbreviation', name=op.f('uq_enterprises_abbreviation')),
    sa.UniqueConstraint('name', name=op.f('uq_enterprises_name'))
    )
    op.create_table('lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_lookups_enterprise_id_enterprises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lookups')),
    sa.UniqueConstraint('enterprise_id', 'name', name=op.f('uq_lookups_enterprise_id'))
    )
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookups_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('measurement_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_measurement_units_enterprise_id_enterprises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurement_units')),
    sa.UniqueConstraint('abbreviation', 'enterprise_id', name=op.f('uq_measurement_units_abbreviation')),
    sa.UniqueConstraint('enterprise_id', 'name', name=op.f('uq_measurement_units_enterprise_id'))
    )
    with op.batch_alter_table('measurement_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_units_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_sites_enterprise_id_enterprises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('abbreviation', 'enterprise_id', name=op.f('uq_sites_abbreviation')),
    sa.UniqueConstraint('enterprise_id', 'name', name=op.f('uq_sites_enterprise_id'))
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_areas_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('abbreviation', 'site_id', name=op.f('uq_areas_abbreviation')),
    sa.UniqueConstraint('name', 'site_id', name=op.f('uq_areas_name'))
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_site_id'), ['site_id'], unique=False)

    op.create_table('lookup_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lookup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], name=op.f('fk_lookup_values_lookup_id_lookups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lookup_values')),
    sa.UniqueConstraint('name', 'lookup_id', name=op.f('uq_lookup_values_name'))
    )
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_values_lookup_id'), ['lookup_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('lookup_id', sa.Integer(), nullable=True),
    sa.Column('measurement_unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_tags_area_id_areas')),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], name=op.f('fk_tags_lookup_id_lookups')),
    sa.ForeignKeyConstraint(['measurement_unit_id'], ['measurement_units.id'], name=op.f('fk_tags_measurement_unit_id_measurement_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('area_id', 'name', name=op.f('uq_tags_area_id'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_lookup_id'), ['lookup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_measurement_unit_id'), ['measurement_unit_id'], unique=False)

    op.create_table('tag_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('lookup_value_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(value IS NOT NULL) + (lookup_value_id IS NOT NULL) = 1', name=op.f('ck_tag_values_value_xor_lookup_value_id')),
    sa.ForeignKeyConstraint(['lookup_value_id'], ['lookup_values.id'], name=op.f('fk_tag_values_lookup_value_id_lookup_values'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_values_tag_id_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_values'))
    )
    with op.batch_alter_table('tag_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_values_lookup_value_id'), ['lookup_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_values_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_values_tag_id'))
        batch_op.drop_index(batch_op.f('ix_tag_values_lookup_value_id'))

    op.drop_table('tag_values')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_measurement_unit_id'))
        batch_op.drop_index(batch_op.f('ix_tags_lookup_id'))
        batch_op.drop_index(batch_op.f('ix_tags_area_id'))

    op.drop_table('tags')
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_values_lookup_id'))

    op.drop_table('lookup_values')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_site_id'))

    op.drop_table('areas')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_enterprise_id'))

    op.drop_table('sites')
    with op.batch_alter_table('measurement_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_units_enterprise_id'))

    op.drop_table('measurement_units')
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookups_enterprise_id'))

    op.drop_table('lookups')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
