"""add event_frame_attribute_templates table

Revision ID: 9a8b0337489e
Revises: 76ca67faa837
Create Date: 2026-07-17 22:28:46.529363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8b0337489e'
down_revision: Union[str, Sequence[str], None] = '76ca67faa837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_frame_attribute_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_frame_template_id', sa.Integer(), nullable=False),
    sa.Column('lookup_id', sa.Integer(), nullable=True),
    sa.Column('measurement_unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_start_value', sa.Float(), nullable=True),
    sa.Column('default_end_value', sa.Float(), nullable=True),
    sa.Column('default_start_lookup_value_id', sa.Integer(), nullable=True),
    sa.Column('default_end_lookup_value_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_end_lookup_value_id'], ['lookup_values.id'], name=op.f('fk_event_frame_attribute_templates_default_end_lookup_value_id_lookup_values')),
    sa.ForeignKeyConstraint(['default_start_lookup_value_id'], ['lookup_values.id'], name=op.f('fk_event_frame_attribute_templates_default_start_lookup_value_id_lookup_values')),
    sa.ForeignKeyConstraint(['event_frame_template_id'], ['event_frame_templates.id'], name=op.f('fk_event_frame_attribute_templates_event_frame_template_id_event_frame_templates')),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], name=op.f('fk_event_frame_attribute_templates_lookup_id_lookups')),
    sa.ForeignKeyConstraint(['measurement_unit_id'], ['measurement_units.id'], name=op.f('fk_event_frame_attribute_templates_measurement_unit_id_measurement_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_frame_attribute_templates')),
    sa.UniqueConstraint('event_frame_template_id', 'name', name=op.f('uq_event_frame_attribute_templates_event_frame_template_id'))
    )
    with op.batch_alter_table('event_frame_attribute_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_frame_attribute_templates_default_end_lookup_value_id'), ['default_end_lookup_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_attribute_templates_default_start_lookup_value_id'), ['default_start_lookup_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_attribute_templates_event_frame_template_id'), ['event_frame_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_attribute_templates_lookup_id'), ['lookup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frame_attribute_templates_measurement_unit_id'), ['measurement_unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_frame_attribute_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_frame_attribute_templates_measurement_unit_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_attribute_templates_lookup_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_attribute_templates_event_frame_template_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_attribute_templates_default_start_lookup_value_id'))
        batch_op.drop_index(batch_op.f('ix_event_frame_attribute_templates_default_end_lookup_value_id'))

    op.drop_table('event_frame_attribute_templates')
    # ### end Alembic commands ###
