"""add event_frames table

Revision ID: ad94e98ab812
Revises: 9a8b0337489e
Create Date: 2026-07-18 02:17:43.488298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad94e98ab812'
down_revision: Union[str, Sequence[str], None] = '9a8b0337489e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('event_frame_template_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name=op.f('ck_event_frames_ended_after_started')),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name=op.f('fk_event_frames_element_id_elements')),
    sa.ForeignKeyConstraint(['event_frame_template_id'], ['event_frame_templates.id'], name=op.f('fk_event_frames_event_frame_template_id_event_frame_templates')),
    sa.ForeignKeyConstraint(['parent_id'], ['event_frames.id'], name=op.f('fk_event_frames_parent_id_event_frames')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_frames'))
    )
    with op.batch_alter_table('event_frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_frames_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frames_event_frame_template_id'), ['event_frame_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_frames_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_frames_parent_id'))
        batch_op.drop_index(batch_op.f('ix_event_frames_event_frame_template_id'))
        batch_op.drop_index(batch_op.f('ix_event_frames_element_id'))

    op.drop_table('event_frames')
    # ### end Alembic commands ###
