"""add enterprises.house_context

Revision ID: b6cacc7323a7
Revises: 75ae90dc029d
Create Date: 2026-07-20 01:24:54.578072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cacc7323a7'
down_revision: Union[str, Sequence[str], None] = '75ae90dc029d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.drop_column('house_context')

    # ### end Alembic commands ###
