"""add element_attributes table

Revision ID: b88bd0361d50
Revises: cf79f49e4ee9
Create Date: 2026-07-11 14:23:12.658480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88bd0361d50'
down_revision: Union[str, Sequence[str], None] = 'cf79f49e4ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('element_attribute_template_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('owns_tag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['element_attribute_template_id'], ['element_attribute_templates.id'], name=op.f('fk_element_attributes_element_attribute_template_id_element_attribute_templates')),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], name=op.f('fk_element_attributes_element_id_elements')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_element_attributes_tag_id_tags'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_element_attributes')),
    sa.UniqueConstraint('element_id', 'element_attribute_template_id', name=op.f('uq_element_attributes_element_id'))
    )
    with op.batch_alter_table('element_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_element_attributes_element_attribute_template_id'), ['element_attribute_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_attributes_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_attributes_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_element_attributes_tag_id'))
        batch_op.drop_index(batch_op.f('ix_element_attributes_element_id'))
        batch_op.drop_index(batch_op.f('ix_element_attributes_element_attribute_template_id'))

    op.drop_table('element_attributes')
    # ### end Alembic commands ###
