"""add element_attribute_templates table

Revision ID: c67d381354a0
Revises: 7b210831a436
Create Date: 2026-07-08 19:59:33.761317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67d381354a0'
down_revision: Union[str, Sequence[str], None] = '7b210831a436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_attribute_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_template_id', sa.Integer(), nullable=False),
    sa.Column('lookup_id', sa.Integer(), nullable=True),
    sa.Column('measurement_unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['element_template_id'], ['element_templates.id'], name=op.f('fk_element_attribute_templates_element_template_id_element_templates')),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], name=op.f('fk_element_attribute_templates_lookup_id_lookups')),
    sa.ForeignKeyConstraint(['measurement_unit_id'], ['measurement_units.id'], name=op.f('fk_element_attribute_templates_measurement_unit_id_measurement_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_element_attribute_templates')),
    sa.UniqueConstraint('element_template_id', 'name', name=op.f('uq_element_attribute_templates_element_template_id'))
    )
    with op.batch_alter_table('element_attribute_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_element_attribute_templates_element_template_id'), ['element_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_attribute_templates_lookup_id'), ['lookup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_attribute_templates_measurement_unit_id'), ['measurement_unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_attribute_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_element_attribute_templates_measurement_unit_id'))
        batch_op.drop_index(batch_op.f('ix_element_attribute_templates_lookup_id'))
        batch_op.drop_index(batch_op.f('ix_element_attribute_templates_element_template_id'))

    op.drop_table('element_attribute_templates')
    # ### end Alembic commands ###
